/*
 * OrdeRS BookStore Sample Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountCodeProperties {
    #[serde(rename = "percentage_discount", skip_serializing_if = "Option::is_none")]
    pub percentage_discount: Option<i32>,
    #[serde(rename = "valid_from", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    #[serde(rename = "valid_to", skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<String>,
}

impl DiscountCodeProperties {
    pub fn new() -> DiscountCodeProperties {
        DiscountCodeProperties {
            percentage_discount: None,
            valid_from: None,
            valid_to: None,
        }
    }
}

