/*
 * OrdeRS BookStore Sample Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Inventory {
    #[serde(rename = "books_available", skip_serializing_if = "Option::is_none")]
    pub books_available: Option<i32>,
    #[serde(rename = "books_reordered", skip_serializing_if = "Option::is_none")]
    pub books_reordered: Option<i32>,
    #[serde(rename = "books_out_of_stock", skip_serializing_if = "Option::is_none")]
    pub books_out_of_stock: Option<i32>,
}

impl Inventory {
    pub fn new() -> Inventory {
        Inventory {
            books_available: None,
            books_reordered: None,
            books_out_of_stock: None,
        }
    }
}

